version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 15
    labels:
      - "area-dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 5
    labels:
      - "area-dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"