name: $(version).$(Rev:r)

variables:
  version: 3.1
  buildConfiguration: "Release"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - src/*
      - .devops/*
      - azure-pipelines.yaml

stages:
  - template: .devops/pipelines/stage.ci.yaml
