using JetBrains.Annotations;

namespace ES.FX.Problems;

/// <summary>
///     Represents a problem (based on RFC 7807 - https://datatracker.ietf.org/doc/html/rfc7807).
/// </summary>
/// <param name="Type">A URI reference [RFC3986] that identifies the problem type. </param>
/// <param name="Title">A short, human-readable summary of the problem type.</param>
/// <param name="Detail">A human-readable explanation specific to this occurrence of the problem.</param>
/// <param name="Instance">
///     A URI reference that identifies the specific occurrence of the problem.It may or may not yield
///     further information if dereferenced.
/// </param>
/// <param name="Status">The status code generated by the origin for this occurrence of a problem.</param>
[PublicAPI]
public record Problem(
    string Type = "about:blank",
    string? Title = null,
    string? Detail = null,
    string? Instance = null,
    int? Status = null);